# Copyright (c) 2024-2025 Henrik Brix Andersen <henrik@brixandersen.dk>
# SPDX-License-Identifier: Apache-2.0

if(SB_CONFIG_CANNECTIVITY_DFU_SUPPORT)
  # TODO: this won't work since sysbuild_get() cannot work until after the CMake build step
  sysbuild_get(app_CONFIG_CANNECTIVITY_DFU_BACKEND_MCUBOOT IMAGE ${DEFAULT_IMAGE} VAR CONFIG_CANNECTIVITY_DFU_BACKEND_MCUBOOT KCONFIG)
  if(app_CONFIG_CANNECTIVITY_DFU_BACKEND_MCUBOOT)
    sysbuild_get(app_CONFIG_CANNECTIVITY_USB_MANUFACTURER IMAGE ${DEFAULT_IMAGE} VAR CONFIG_CANNECTIVITY_USB_MANUFACTURER KCONFIG)
    sysbuild_get(app_CONFIG_CANNECTIVITY_USB_DFU_PRODUCT IMAGE ${DEFAULT_IMAGE} VAR CONFIG_CANNECTIVITY_USB_DFU_PRODUCT KCONFIG)
    sysbuild_get(app_CONFIG_CANNECTIVITY_USB_DFU_VID IMAGE ${DEFAULT_IMAGE} VAR CONFIG_CANNECTIVITY_USB_DFU_VID KCONFIG)
    sysbuild_get(app_CONFIG_CANNECTIVITY_USB_DFU_PID IMAGE ${DEFAULT_IMAGE} VAR CONFIG_CANNECTIVITY_USB_DFU_PID KCONFIG)
    sysbuild_get(app_CONFIG_CANNECTIVITY_USB_MAX_POWER IMAGE ${DEFAULT_IMAGE} VAR CONFIG_CANNECTIVITY_USB_MAX_POWER KCONFIG)

    # Override MCUboot options with those from the CANnectivity firmware app
    set_config_string(mcuboot CONFIG_USB_DEVICE_MANUFACTURER "${app_CONFIG_CANNECTIVITY_USB_MANUFACTURER}")
    set_config_string(mcuboot CONFIG_USB_DEVICE_PRODUCT "${app_CONFIG_CANNECTIVITY_USB_DFU_PRODUCT}")
    set_config_int(mcuboot CONFIG_USB_DEVICE_VID ${app_CONFIG_CANNECTIVITY_USB_DFU_VID})
    set_config_int(mcuboot CONFIG_USB_DEVICE_PID ${app_CONFIG_CANNECTIVITY_USB_DFU_PID})
    set_config_int(mcuboot CONFIG_USB_DEVICE_DFU_PID ${app_CONFIG_CANNECTIVITY_USB_DFU_PID})
    set_config_int(mcuboot CONFIG_USB_MAX_POWER ${app_CONFIG_CANNECTIVITY_USB_MAX_POWER})
  endif()
endif()
