# Copyright (c) 2025 Henrik Brix Andersen <henrik@brixandersen.dk>
# SPDX-License-Identifier: Apache-2.0

CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_USBD_DFU_FLASH_SLOT0=n
CONFIG_USBD_DFU_FLASH_SLOT1=y
CONFIG_USBD_DFU_NUMOF_IMAGES=1
